scoreboard objectives add spread_z dummy
scoreboard objectives add spread_x dummy
scoreboard objectives add line_b dummy
scoreboard objectives add cdi_const dummy
scoreboard objectives add variant dummy
scoreboard objectives add cooldown dummy
scoreboard objectives add lvltick dummy
scoreboard objectives add state dummy
scoreboard objectives add biome_d dummy
scoreboard objectives add exp_17 dummy
scoreboard objectives add exp_18 dummy
scoreboard objectives add exp_19 dummy
scoreboard objectives add level dummy
scoreboard objectives add weapon_0 dummy
scoreboard objectives add exp_10 dummy
scoreboard objectives add weapon_2 dummy
scoreboard objectives add exp_11 dummy
scoreboard objectives add weapon_1 dummy
scoreboard objectives add exp_12 dummy
scoreboard objectives add exp_13 dummy
scoreboard objectives add exp_14 dummy
scoreboard objectives add exp_15 dummy
scoreboard objectives add line_t dummy
scoreboard objectives add exp_16 dummy
scoreboard objectives add weapon_8 dummy
scoreboard objectives add weapon_7 dummy
scoreboard objectives add weapon_9 dummy
scoreboard objectives add weapon_4 dummy
scoreboard objectives add weapon_3 dummy
scoreboard objectives add weapon_6 dummy
scoreboard objectives add biome dummy
scoreboard objectives add weapon_5 dummy
scoreboard objectives add monster_c dummy
scoreboard objectives add npc_c dummy
scoreboard objectives add exp_1 dummy
scoreboard objectives add exp_0 dummy
scoreboard objectives add dead dummy
scoreboard objectives add global dummy
scoreboard objectives add cycle dummy
scoreboard objectives add delete dummy
scoreboard objectives add exp_9 dummy
scoreboard objectives add weapon dummy
scoreboard objectives add exp_8 dummy
scoreboard objectives add exp_7 dummy
scoreboard objectives add found dummy
scoreboard objectives add exp_6 dummy
scoreboard objectives add exp_5 dummy
scoreboard objectives add exp_4 dummy
scoreboard objectives add exp_3 dummy
scoreboard objectives add exp_2 dummy
scoreboard objectives add player dummy
scoreboard objectives add temp dummy
scoreboard objectives add chance dummy
scoreboard objectives add sandbox dummy
scoreboard objectives add store dummy
scoreboard objectives add op0 dummy
scoreboard objectives add monster dummy
scoreboard objectives add weapon_11 dummy
scoreboard objectives add weapon_10 dummy
scoreboard objectives add weapon_13 dummy
scoreboard objectives add weapon_12 dummy
scoreboard objectives add weapon_15 dummy
scoreboard objectives add weapon_14 dummy
scoreboard objectives add weapon_17 dummy
scoreboard objectives add weapon_16 dummy
scoreboard objectives add weapon_19 dummy
scoreboard objectives add weapon_18 dummy
scoreboard players set "#500" cdi_const 500
