tag @s add sound.music.meadows
tag @s remove sound.music.none
tag @s remove sound.music.thawing
tag @s remove sound.music.ruins
tag @s remove sound.music.quarry
tag @s remove sound.music.town
tag @s remove sound.music.marshes
tag @s remove sound.music.lake
tag @s remove sound.music.dungeons
tag @s remove sound.music.forest