scoreboard players set @s exp_0 30
scoreboard players set @s weapon_0 3
scoreboard players set @s exp_1 30
scoreboard players set @s weapon_1 3
scoreboard players set @s exp_2 30
scoreboard players set @s weapon_2 3
scoreboard players set @s exp_3 30
scoreboard players set @s weapon_3 3
scoreboard players set @s exp_4 30
scoreboard players set @s weapon_4 3
scoreboard players set @s exp_5 30
scoreboard players set @s weapon_5 3
scoreboard players set @s exp_6 30
scoreboard players set @s weapon_6 3
scoreboard players set @s exp_7 30
scoreboard players set @s weapon_7 3
scoreboard players set @s exp_8 30
scoreboard players set @s weapon_8 3
scoreboard players set @s exp_9 30
scoreboard players set @s weapon_9 3
scoreboard players set @s exp_10 30
scoreboard players set @s weapon_10 3
scoreboard players set @s exp_11 30
scoreboard players set @s weapon_11 3
scoreboard players set @s exp_12 30
scoreboard players set @s weapon_12 3
scoreboard players set @s exp_13 30
scoreboard players set @s weapon_13 3
scoreboard players set @s exp_14 30
scoreboard players set @s weapon_14 3
scoreboard players set @s exp_15 30
scoreboard players set @s weapon_15 3
scoreboard players set @s exp_16 30
scoreboard players set @s weapon_16 3
scoreboard players set @s exp_17 30
scoreboard players set @s weapon_17 3
scoreboard players set @s exp_18 30
scoreboard players set @s weapon_18 3
scoreboard players set @s exp_19 30
scoreboard players set @s weapon_19 3
