scoreboard players set @s exp_0 0
scoreboard players set @s weapon_0 1
scoreboard players set @s exp_1 0
scoreboard players set @s weapon_1 1
scoreboard players set @s exp_2 0
scoreboard players set @s weapon_2 1
scoreboard players set @s exp_3 0
scoreboard players set @s weapon_3 1
scoreboard players set @s exp_4 0
scoreboard players set @s weapon_4 1
scoreboard players set @s exp_5 0
scoreboard players set @s weapon_5 1
scoreboard players set @s exp_6 0
scoreboard players set @s weapon_6 1
scoreboard players set @s exp_7 0
scoreboard players set @s weapon_7 1
scoreboard players set @s exp_8 0
scoreboard players set @s weapon_8 1
scoreboard players set @s exp_9 0
scoreboard players set @s weapon_9 1
scoreboard players set @s exp_10 0
scoreboard players set @s weapon_10 1
scoreboard players set @s exp_11 0
scoreboard players set @s weapon_11 1
scoreboard players set @s exp_12 0
scoreboard players set @s weapon_12 1
scoreboard players set @s exp_13 0
scoreboard players set @s weapon_13 1
scoreboard players set @s exp_14 0
scoreboard players set @s weapon_14 1
scoreboard players set @s exp_15 0
scoreboard players set @s weapon_15 1
scoreboard players set @s exp_16 0
scoreboard players set @s weapon_16 1
scoreboard players set @s exp_17 0
scoreboard players set @s weapon_17 1
scoreboard players set @s exp_18 0
scoreboard players set @s weapon_18 1
scoreboard players set @s exp_19 0
scoreboard players set @s weapon_19 1
