scoreboard players set @s exp_0 10
scoreboard players set @s weapon_0 2
scoreboard players set @s exp_1 10
scoreboard players set @s weapon_1 2
scoreboard players set @s exp_2 10
scoreboard players set @s weapon_2 2
scoreboard players set @s exp_3 10
scoreboard players set @s weapon_3 2
scoreboard players set @s exp_4 10
scoreboard players set @s weapon_4 2
scoreboard players set @s exp_5 10
scoreboard players set @s weapon_5 2
scoreboard players set @s exp_6 10
scoreboard players set @s weapon_6 2
scoreboard players set @s exp_7 10
scoreboard players set @s weapon_7 2
scoreboard players set @s exp_8 10
scoreboard players set @s weapon_8 2
scoreboard players set @s exp_9 10
scoreboard players set @s weapon_9 2
scoreboard players set @s exp_10 10
scoreboard players set @s weapon_10 2
scoreboard players set @s exp_11 10
scoreboard players set @s weapon_11 2
scoreboard players set @s exp_12 10
scoreboard players set @s weapon_12 2
scoreboard players set @s exp_13 10
scoreboard players set @s weapon_13 2
scoreboard players set @s exp_14 10
scoreboard players set @s weapon_14 2
scoreboard players set @s exp_15 10
scoreboard players set @s weapon_15 2
scoreboard players set @s exp_16 10
scoreboard players set @s weapon_16 2
scoreboard players set @s exp_17 10
scoreboard players set @s weapon_17 2
scoreboard players set @s exp_18 10
scoreboard players set @s weapon_18 2
scoreboard players set @s exp_19 10
scoreboard players set @s weapon_19 2
