function opw/util/books/s_sword
function opw/util/books/s_sun
function opw/util/books/ce_galaxy
function opw/util/books/ce_wand
function opw/util/books/ch_hammer
function opw/util/books/ch_lantern
function opw/util/books/dk_knights
function opw/util/books/dk_lance
function opw/util/books/d_axe
function opw/util/books/d_hand
function opw/util/books/f_crystal
function opw/util/books/f_dagger
function opw/util/books/l_staff
function opw/util/books/l_blade
function opw/util/books/n_staff
function opw/util/books/n_sword
function opw/util/books/p_bow
function opw/util/books/p_swamp
function opw/util/books/r_gauntlets
function opw/util/books/r_spear
function opw/util/books/guide
