execute @s[scores={weapon_18=0},hasitem={item=opw:ce_galaxy}] ~ ~ ~ function opw/weapon/ce_galaxy/share
execute @s[scores={weapon_19=0},hasitem={item=opw:ce_wand}] ~ ~ ~ function opw/weapon/ce_wand/share
execute @s[scores={weapon_2=0},hasitem={item=opw:ch_hammer}] ~ ~ ~ function opw/weapon/ch_hammer/share
execute @s[scores={weapon_3=0},hasitem={item=opw:ch_lantern}] ~ ~ ~ function opw/weapon/ch_lantern/share
execute @s[scores={weapon_4=0},hasitem={item=opw:dk_knights}] ~ ~ ~ function opw/weapon/dk_knights/share
execute @s[scores={weapon_5=0},hasitem={item=opw:dk_lance}] ~ ~ ~ function opw/weapon/dk_lance/share
execute @s[scores={weapon_6=0},hasitem={item=opw:d_axe}] ~ ~ ~ function opw/weapon/d_axe/share
execute @s[scores={weapon_7=0},hasitem={item=opw:d_hand}] ~ ~ ~ function opw/weapon/d_hand/share
execute @s[scores={weapon_8=0},hasitem={item=opw:f_crystal}] ~ ~ ~ function opw/weapon/f_crystal/share
execute @s[scores={weapon_9=0},hasitem={item=opw:f_dagger}] ~ ~ ~ function opw/weapon/f_dagger/share
execute @s[scores={weapon_10=0},hasitem={item=opw:l_blade}] ~ ~ ~ function opw/weapon/l_blade/share
execute @s[scores={weapon_11=0},hasitem={item=opw:l_staff}] ~ ~ ~ function opw/weapon/l_staff/share
execute @s[scores={weapon_12=0},hasitem={item=opw:n_staff}] ~ ~ ~ function opw/weapon/n_staff/share
execute @s[scores={weapon_13=0},hasitem={item=opw:n_sword}] ~ ~ ~ function opw/weapon/n_sword/share
execute @s[scores={weapon_14=0},hasitem={item=opw:p_bow}] ~ ~ ~ function opw/weapon/p_bow/share
execute @s[scores={weapon_15=0},hasitem={item=opw:p_swamp}] ~ ~ ~ function opw/weapon/p_swamp/share
execute @s[scores={weapon_16=0},hasitem={item=opw:r_gauntlets}] ~ ~ ~ function opw/weapon/r_gauntlets/share
execute @s[scores={weapon_17=0},hasitem={item=opw:r_spear}] ~ ~ ~ function opw/weapon/r_spear/share
execute @s[scores={weapon_1=0},hasitem={item=opw:s_sun}] ~ ~ ~ function opw/weapon/s_sun/share
execute @s[scores={weapon_0=0},hasitem={item=opw:s_sword}] ~ ~ ~ function opw/weapon/s_sword/share
