scoreboard players set @s weapon_18 1
scoreboard players set @s weapon_19 1
scoreboard players set @s weapon_2 1
scoreboard players set @s weapon_3 1
scoreboard players set @s weapon_4 1
scoreboard players set @s weapon_5 1
scoreboard players set @s weapon_6 1
scoreboard players set @s weapon_7 1
scoreboard players set @s weapon_8 1
scoreboard players set @s weapon_9 1
scoreboard players set @s weapon_10 1
scoreboard players set @s weapon_11 1
scoreboard players set @s weapon_12 1
scoreboard players set @s weapon_13 1
scoreboard players set @s weapon_14 1
scoreboard players set @s weapon_15 1
scoreboard players set @s weapon_16 1
scoreboard players set @s weapon_17 1
scoreboard players set @s weapon_1 1
scoreboard players set @s weapon_0 1
