execute @s[name="§r§fGalaxy Sphere [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/ce_galaxy_0
execute @s[name="§r§fCelestial Wand [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/ce_wand_0
execute @s[name="§r§fChaos Hammer [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/ch_hammer_0
execute @s[name="§r§fLantern of Souls [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/ch_lantern_0
execute @s[name="§r§fDeath Knight's Head [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/dk_knights_0
execute @s[name="§r§fSoul Stealer [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/dk_lance_0
execute @s[name="§r§fDemon Cleaver [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/d_axe_0
execute @s[name="§r§fDemon King's Hand [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/d_hand_0
execute @s[name="§r§fFrost Chakram [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/f_crystal_0
execute @s[name="§r§fFrost Fang [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/f_dagger_0
execute @s[name="§r§fLightning Sword [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/l_blade_0
execute @s[name="§r§fLightning Staff [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/l_staff_0
execute @s[name="§r§fBramble Staff [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/n_staff_0
execute @s[name="§r§fGale Blade [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/n_sword_0
execute @s[name="§r§fBlight Bow [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/p_bow_0
execute @s[name="§r§fSwamp Pendant [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/p_swamp_0
execute @s[name="§r§fRoyal Gauntlet [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/r_gauntlets_0
execute @s[name="§r§fRoyal Spear [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/r_spear_0
execute @s[name="§r§fSolar Sun [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/s_sun_0
execute @s[name="§r§fSolar Sword [§9Destructive§f]"] ~ ~ ~ function opw/inventory/drop/s_sword_0
execute @s[name="§r§fGalaxy Sphere [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/ce_galaxy_1
execute @s[name="§r§fCelestial Wand [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/ce_wand_1
execute @s[name="§r§fChaos Hammer [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/ch_hammer_1
execute @s[name="§r§fLantern of Souls [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/ch_lantern_1
execute @s[name="§r§fDeath Knight's Head [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/dk_knights_1
execute @s[name="§r§fSoul Stealer [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/dk_lance_1
execute @s[name="§r§fDemon Cleaver [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/d_axe_1
execute @s[name="§r§fDemon King's Hand [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/d_hand_1
execute @s[name="§r§fFrost Chakram [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/f_crystal_1
execute @s[name="§r§fFrost Fang [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/f_dagger_1
execute @s[name="§r§fLightning Sword [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/l_blade_1
execute @s[name="§r§fLightning Staff [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/l_staff_1
execute @s[name="§r§fBramble Staff [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/n_staff_1
execute @s[name="§r§fGale Blade [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/n_sword_1
execute @s[name="§r§fBlight Bow [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/p_bow_1
execute @s[name="§r§fSwamp Pendant [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/p_swamp_1
execute @s[name="§r§fRoyal Gauntlet [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/r_gauntlets_1
execute @s[name="§r§fRoyal Spear [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/r_spear_1
execute @s[name="§r§fSolar Sun [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/s_sun_1
execute @s[name="§r§fSolar Sword [§dTitanic§f]"] ~ ~ ~ function opw/inventory/drop/s_sword_1
execute @s[name="§r§fGalaxy Sphere [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/ce_galaxy_2
execute @s[name="§r§fCelestial Wand [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/ce_wand_2
execute @s[name="§r§fChaos Hammer [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/ch_hammer_2
execute @s[name="§r§fLantern of Souls [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/ch_lantern_2
execute @s[name="§r§fDeath Knight's Head [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/dk_knights_2
execute @s[name="§r§fSoul Stealer [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/dk_lance_2
execute @s[name="§r§fDemon Cleaver [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/d_axe_2
execute @s[name="§r§fDemon King's Hand [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/d_hand_2
execute @s[name="§r§fFrost Chakram [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/f_crystal_2
execute @s[name="§r§fFrost Fang [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/f_dagger_2
execute @s[name="§r§fLightning Sword [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/l_blade_2
execute @s[name="§r§fLightning Staff [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/l_staff_2
execute @s[name="§r§fBramble Staff [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/n_staff_2
execute @s[name="§r§fGale Blade [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/n_sword_2
execute @s[name="§r§fBlight Bow [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/p_bow_2
execute @s[name="§r§fSwamp Pendant [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/p_swamp_2
execute @s[name="§r§fRoyal Gauntlet [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/r_gauntlets_2
execute @s[name="§r§fRoyal Spear [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/r_spear_2
execute @s[name="§r§fSolar Sun [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/s_sun_2
execute @s[name="§r§fSolar Sword [§cApocalyptic§f]"] ~ ~ ~ function opw/inventory/drop/s_sword_2
