scoreboard players add @s weapon_18 0
scoreboard players add @s weapon_19 0
scoreboard players add @s weapon_2 0
scoreboard players add @s weapon_3 0
scoreboard players add @s weapon_4 0
scoreboard players add @s weapon_5 0
scoreboard players add @s weapon_6 0
scoreboard players add @s weapon_7 0
scoreboard players add @s weapon_8 0
scoreboard players add @s weapon_9 0
scoreboard players add @s weapon_10 0
scoreboard players add @s weapon_11 0
scoreboard players add @s weapon_12 0
scoreboard players add @s weapon_13 0
scoreboard players add @s weapon_14 0
scoreboard players add @s weapon_15 0
scoreboard players add @s weapon_16 0
scoreboard players add @s weapon_17 0
scoreboard players add @s weapon_1 0
scoreboard players add @s weapon_0 0
