playanimation @s[scores={weapon_18=!0},tag=!has.weapon.18] update_weapon_18 default 0 "v.weapon_18 = 1; return 1;" inventory_18
playanimation @s[scores={weapon_18=!0},tag=has.weapon.18] grab_weapon_18 default 0 "v.weapon_18 = 2; return 1;" inventory_18
playanimation @s[scores={weapon_19=!0},tag=!has.weapon.19] update_weapon_19 default 0 "v.weapon_19 = 1; return 1;" inventory_19
playanimation @s[scores={weapon_19=!0},tag=has.weapon.19] grab_weapon_19 default 0 "v.weapon_19 = 2; return 1;" inventory_19
playanimation @s[scores={weapon_2=!0},tag=!has.weapon.2] update_weapon_2 default 0 "v.weapon_2 = 1; return 1;" inventory_2
playanimation @s[scores={weapon_2=!0},tag=has.weapon.2] grab_weapon_2 default 0 "v.weapon_2 = 2; return 1;" inventory_2
playanimation @s[scores={weapon_3=!0},tag=!has.weapon.3] update_weapon_3 default 0 "v.weapon_3 = 1; return 1;" inventory_3
playanimation @s[scores={weapon_3=!0},tag=has.weapon.3] grab_weapon_3 default 0 "v.weapon_3 = 2; return 1;" inventory_3
playanimation @s[scores={weapon_4=!0},tag=!has.weapon.4] update_weapon_4 default 0 "v.weapon_4 = 1; return 1;" inventory_4
playanimation @s[scores={weapon_4=!0},tag=has.weapon.4] grab_weapon_4 default 0 "v.weapon_4 = 2; return 1;" inventory_4
playanimation @s[scores={weapon_5=!0},tag=!has.weapon.5] update_weapon_5 default 0 "v.weapon_5 = 1; return 1;" inventory_5
playanimation @s[scores={weapon_5=!0},tag=has.weapon.5] grab_weapon_5 default 0 "v.weapon_5 = 2; return 1;" inventory_5
playanimation @s[scores={weapon_6=!0},tag=!has.weapon.6] update_weapon_6 default 0 "v.weapon_6 = 1; return 1;" inventory_6
playanimation @s[scores={weapon_6=!0},tag=has.weapon.6] grab_weapon_6 default 0 "v.weapon_6 = 2; return 1;" inventory_6
playanimation @s[scores={weapon_7=!0},tag=!has.weapon.7] update_weapon_7 default 0 "v.weapon_7 = 1; return 1;" inventory_7
playanimation @s[scores={weapon_7=!0},tag=has.weapon.7] grab_weapon_7 default 0 "v.weapon_7 = 2; return 1;" inventory_7
playanimation @s[scores={weapon_8=!0},tag=!has.weapon.8] update_weapon_8 default 0 "v.weapon_8 = 1; return 1;" inventory_8
playanimation @s[scores={weapon_8=!0},tag=has.weapon.8] grab_weapon_8 default 0 "v.weapon_8 = 2; return 1;" inventory_8
playanimation @s[scores={weapon_9=!0},tag=!has.weapon.9] update_weapon_9 default 0 "v.weapon_9 = 1; return 1;" inventory_9
playanimation @s[scores={weapon_9=!0},tag=has.weapon.9] grab_weapon_9 default 0 "v.weapon_9 = 2; return 1;" inventory_9
playanimation @s[scores={weapon_10=!0},tag=!has.weapon.10] update_weapon_10 default 0 "v.weapon_10 = 1; return 1;" inventory_10
playanimation @s[scores={weapon_10=!0},tag=has.weapon.10] grab_weapon_10 default 0 "v.weapon_10 = 2; return 1;" inventory_10
playanimation @s[scores={weapon_11=!0},tag=!has.weapon.11] update_weapon_11 default 0 "v.weapon_11 = 1; return 1;" inventory_11
playanimation @s[scores={weapon_11=!0},tag=has.weapon.11] grab_weapon_11 default 0 "v.weapon_11 = 2; return 1;" inventory_11
playanimation @s[scores={weapon_12=!0},tag=!has.weapon.12] update_weapon_12 default 0 "v.weapon_12 = 1; return 1;" inventory_12
playanimation @s[scores={weapon_12=!0},tag=has.weapon.12] grab_weapon_12 default 0 "v.weapon_12 = 2; return 1;" inventory_12
playanimation @s[scores={weapon_13=!0},tag=!has.weapon.13] update_weapon_13 default 0 "v.weapon_13 = 1; return 1;" inventory_13
playanimation @s[scores={weapon_13=!0},tag=has.weapon.13] grab_weapon_13 default 0 "v.weapon_13 = 2; return 1;" inventory_13
playanimation @s[scores={weapon_14=!0},tag=!has.weapon.14] update_weapon_14 default 0 "v.weapon_14 = 1; return 1;" inventory_14
playanimation @s[scores={weapon_14=!0},tag=has.weapon.14] grab_weapon_14 default 0 "v.weapon_14 = 2; return 1;" inventory_14
playanimation @s[scores={weapon_15=!0},tag=!has.weapon.15] update_weapon_15 default 0 "v.weapon_15 = 1; return 1;" inventory_15
playanimation @s[scores={weapon_15=!0},tag=has.weapon.15] grab_weapon_15 default 0 "v.weapon_15 = 2; return 1;" inventory_15
playanimation @s[scores={weapon_16=!0},tag=!has.weapon.16] update_weapon_16 default 0 "v.weapon_16 = 1; return 1;" inventory_16
playanimation @s[scores={weapon_16=!0},tag=has.weapon.16] grab_weapon_16 default 0 "v.weapon_16 = 2; return 1;" inventory_16
playanimation @s[scores={weapon_17=!0},tag=!has.weapon.17] update_weapon_17 default 0 "v.weapon_17 = 1; return 1;" inventory_17
playanimation @s[scores={weapon_17=!0},tag=has.weapon.17] grab_weapon_17 default 0 "v.weapon_17 = 2; return 1;" inventory_17
playanimation @s[scores={weapon_1=!0},tag=!has.weapon.1] update_weapon_1 default 0 "v.weapon_1 = 1; return 1;" inventory_1
playanimation @s[scores={weapon_1=!0},tag=has.weapon.1] grab_weapon_1 default 0 "v.weapon_1 = 2; return 1;" inventory_1
playanimation @s[scores={weapon_0=!0},tag=!has.weapon.0] update_weapon_0 default 0 "v.weapon_0 = 1; return 1;" inventory_0
playanimation @s[scores={weapon_0=!0},tag=has.weapon.0] grab_weapon_0 default 0 "v.weapon_0 = 2; return 1;" inventory_0
