scoreboard players random @s spread_x -14 14
scoreboard players random @s spread_z -14 14
execute @s[scores={spread_x=-14}] ~ ~ ~ tp @s ^-14 ^ ^
execute @s[scores={spread_z=-14}] ~ ~ ~ tp @s ^ ^ ^-14
execute @s[scores={spread_x=-13}] ~ ~ ~ tp @s ^-13 ^ ^
execute @s[scores={spread_z=-13}] ~ ~ ~ tp @s ^ ^ ^-13
execute @s[scores={spread_x=-12}] ~ ~ ~ tp @s ^-12 ^ ^
execute @s[scores={spread_z=-12}] ~ ~ ~ tp @s ^ ^ ^-12
execute @s[scores={spread_x=-11}] ~ ~ ~ tp @s ^-11 ^ ^
execute @s[scores={spread_z=-11}] ~ ~ ~ tp @s ^ ^ ^-11
execute @s[scores={spread_x=-10}] ~ ~ ~ tp @s ^-10 ^ ^
execute @s[scores={spread_z=-10}] ~ ~ ~ tp @s ^ ^ ^-10
execute @s[scores={spread_x=-9}] ~ ~ ~ tp @s ^-9 ^ ^
execute @s[scores={spread_z=-9}] ~ ~ ~ tp @s ^ ^ ^-9
execute @s[scores={spread_x=-8}] ~ ~ ~ tp @s ^-8 ^ ^
execute @s[scores={spread_z=-8}] ~ ~ ~ tp @s ^ ^ ^-8
execute @s[scores={spread_x=-7}] ~ ~ ~ tp @s ^-7 ^ ^
execute @s[scores={spread_z=-7}] ~ ~ ~ tp @s ^ ^ ^-7
execute @s[scores={spread_x=-6}] ~ ~ ~ tp @s ^-6 ^ ^
execute @s[scores={spread_z=-6}] ~ ~ ~ tp @s ^ ^ ^-6
execute @s[scores={spread_x=-5}] ~ ~ ~ tp @s ^-5 ^ ^
execute @s[scores={spread_z=-5}] ~ ~ ~ tp @s ^ ^ ^-5
execute @s[scores={spread_x=-4}] ~ ~ ~ tp @s ^-4 ^ ^
execute @s[scores={spread_z=-4}] ~ ~ ~ tp @s ^ ^ ^-4
execute @s[scores={spread_x=-3}] ~ ~ ~ tp @s ^-3 ^ ^
execute @s[scores={spread_z=-3}] ~ ~ ~ tp @s ^ ^ ^-3
execute @s[scores={spread_x=-2}] ~ ~ ~ tp @s ^-2 ^ ^
execute @s[scores={spread_z=-2}] ~ ~ ~ tp @s ^ ^ ^-2
execute @s[scores={spread_x=-1}] ~ ~ ~ tp @s ^-1 ^ ^
execute @s[scores={spread_z=-1}] ~ ~ ~ tp @s ^ ^ ^-1
execute @s[scores={spread_x=0}] ~ ~ ~ tp @s ^ ^ ^
execute @s[scores={spread_z=0}] ~ ~ ~ tp @s ^ ^ ^
execute @s[scores={spread_x=1}] ~ ~ ~ tp @s ^1 ^ ^
execute @s[scores={spread_z=1}] ~ ~ ~ tp @s ^ ^ ^1
execute @s[scores={spread_x=2}] ~ ~ ~ tp @s ^2 ^ ^
execute @s[scores={spread_z=2}] ~ ~ ~ tp @s ^ ^ ^2
execute @s[scores={spread_x=3}] ~ ~ ~ tp @s ^3 ^ ^
execute @s[scores={spread_z=3}] ~ ~ ~ tp @s ^ ^ ^3
execute @s[scores={spread_x=4}] ~ ~ ~ tp @s ^4 ^ ^
execute @s[scores={spread_z=4}] ~ ~ ~ tp @s ^ ^ ^4
execute @s[scores={spread_x=5}] ~ ~ ~ tp @s ^5 ^ ^
execute @s[scores={spread_z=5}] ~ ~ ~ tp @s ^ ^ ^5
execute @s[scores={spread_x=6}] ~ ~ ~ tp @s ^6 ^ ^
execute @s[scores={spread_z=6}] ~ ~ ~ tp @s ^ ^ ^6
execute @s[scores={spread_x=7}] ~ ~ ~ tp @s ^7 ^ ^
execute @s[scores={spread_z=7}] ~ ~ ~ tp @s ^ ^ ^7
execute @s[scores={spread_x=8}] ~ ~ ~ tp @s ^8 ^ ^
execute @s[scores={spread_z=8}] ~ ~ ~ tp @s ^ ^ ^8
execute @s[scores={spread_x=9}] ~ ~ ~ tp @s ^9 ^ ^
execute @s[scores={spread_z=9}] ~ ~ ~ tp @s ^ ^ ^9
execute @s[scores={spread_x=10}] ~ ~ ~ tp @s ^10 ^ ^
execute @s[scores={spread_z=10}] ~ ~ ~ tp @s ^ ^ ^10
execute @s[scores={spread_x=11}] ~ ~ ~ tp @s ^11 ^ ^
execute @s[scores={spread_z=11}] ~ ~ ~ tp @s ^ ^ ^11
execute @s[scores={spread_x=12}] ~ ~ ~ tp @s ^12 ^ ^
execute @s[scores={spread_z=12}] ~ ~ ~ tp @s ^ ^ ^12
execute @s[scores={spread_x=13}] ~ ~ ~ tp @s ^13 ^ ^
execute @s[scores={spread_z=13}] ~ ~ ~ tp @s ^ ^ ^13
