fog @s remove celestial_fog
fog @s remove chaos_fog
fog @s remove death_fog
fog @s remove demon_fog
fog @s remove frost_fog
fog @s remove lightning_fog
fog @s remove nature_fog
fog @s remove poison_fog
fog @s remove royal_fog
fog @s remove solar_fog
fog @a remove lobby_fog
fog @a remove start_fog
fog @s remove town
fog @s remove meadow
fog @s remove lake
fog @s remove forest
fog @s remove thawing
fog @s remove swamp
fog @s remove gorge
fog @s remove ruins
